// Code generated by t1 - DO NOT EDIT.

package testscriptusage

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "context"
import "io"
import "bytes"

func withParameters(a string, b string, c int) t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_withParameters_1056`,
		Function: `function __t1_withParameters_1056(a, b, c){console.log(a, b, c);
}`,
		Call:       t1.SafeScript(`__t1_withParameters_1056`, a, b, c),
		CallInline: t1.SafeScriptInline(`__t1_withParameters_1056`, a, b, c),
	}
}

func withoutParameters() t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_withoutParameters_6bbf`,
		Function: `function __t1_withoutParameters_6bbf(){alert("hello");
}`,
		Call:       t1.SafeScript(`__t1_withoutParameters_6bbf`),
		CallInline: t1.SafeScriptInline(`__t1_withoutParameters_6bbf`),
	}
}

func onClick() t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_onClick_657d`,
		Function: `function __t1_onClick_657d(){alert("clicked");
}`,
		Call:       t1.SafeScript(`__t1_onClick_657d`),
		CallInline: t1.SafeScriptInline(`__t1_onClick_657d`),
	}
}

func Button(text string) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		t1_7745c5c3_Err = t1.RenderScriptItems(ctx, t1_7745c5c3_Buffer, withParameters("test", text, 123), withoutParameters())
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<button onClick=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var2 t1.ComponentScript = withParameters("test", text, 123)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1_7745c5c3_Var2.Call)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" onMouseover=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var3 t1.ComponentScript = withoutParameters()
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1_7745c5c3_Var3.Call)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" type=\"button\">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var4 string
		t1_7745c5c3_Var4, t1_7745c5c3_Err = t1.JoinStringErrs(text)
		if t1_7745c5c3_Err != nil {
			return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-script-usage/template.t1`, Line: 15, Col: 111}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var4))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</button>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}

func withComment() t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_withComment_9cf8`,
		Function: `function __t1_withComment_9cf8(){//'
}`,
		Call:       t1.SafeScript(`__t1_withComment_9cf8`),
		CallInline: t1.SafeScriptInline(`__t1_withComment_9cf8`),
	}
}

func ThreeButtons() t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var5 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var5 == nil {
			t1_7745c5c3_Var5 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		t1_7745c5c3_Err = Button("A").Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = Button("B").Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<button onMouseover=\"console.log(&#39;mouseover&#39;)\" type=\"button\">Button C</button> <button hx-on::click=\"alert(&#39;clicked inline&#39;)\" type=\"button\">Button D</button> ")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = t1.RenderScriptItems(ctx, t1_7745c5c3_Buffer, onClick())
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<button hx-on::click=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		var t1_7745c5c3_Var6 t1.ComponentScript = onClick()
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1_7745c5c3_Var6.Call)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\" type=\"button\">Button E</button>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = Conditional(true).Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}

func conditionalScript() t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_conditionalScript_de41`,
		Function: `function __t1_conditionalScript_de41(){alert("conditional");
}`,
		Call:       t1.SafeScript(`__t1_conditionalScript_de41`),
		CallInline: t1.SafeScriptInline(`__t1_conditionalScript_de41`),
	}
}

func Conditional(show bool) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var7 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var7 == nil {
			t1_7745c5c3_Var7 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		t1_7745c5c3_Err = t1.RenderScriptItems(ctx, t1_7745c5c3_Buffer, conditionalScript())
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<input type=\"button\" value=\"Click me\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if show {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(" onclick=\"")
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
			var t1_7745c5c3_Var8 t1.ComponentScript = conditionalScript()
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1_7745c5c3_Var8.Call)
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\"")
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
