// Code generated by t1 - DO NOT EDIT.

package testtemplelement

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/t1"
import "context"
import "io"
import "bytes"

import "fmt"

func wrapper(index int) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<div id=\"")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(fmt.Sprint(index)))
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("\">")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = t1_7745c5c3_Var1.Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</div>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}

func template() t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var2 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var2 == nil {
			t1_7745c5c3_Var2 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		t1_7745c5c3_Var3 := t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
			t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
			if !t1_7745c5c3_IsBuffer {
				t1_7745c5c3_Buffer = t1.GetBuffer()
				defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("child1")
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
			t1_7745c5c3_Var4 := t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
				t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
				if !t1_7745c5c3_IsBuffer {
					t1_7745c5c3_Buffer = t1.GetBuffer()
					defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
				}
				_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("child2")
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				t1_7745c5c3_Var5 := t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
					t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
					if !t1_7745c5c3_IsBuffer {
						t1_7745c5c3_Buffer = t1.GetBuffer()
						defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
					}
					_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("child3")
					if t1_7745c5c3_Err != nil {
						return t1_7745c5c3_Err
					}
					t1_7745c5c3_Err = wrapper(4).Render(ctx, t1_7745c5c3_Buffer)
					if t1_7745c5c3_Err != nil {
						return t1_7745c5c3_Err
					}
					if !t1_7745c5c3_IsBuffer {
						_, t1_7745c5c3_Err = io.Copy(t1_7745c5c3_W, t1_7745c5c3_Buffer)
					}
					return t1_7745c5c3_Err
				})
				t1_7745c5c3_Err = wrapper(3).Render(t1.WithChildren(ctx, t1_7745c5c3_Var5), t1_7745c5c3_Buffer)
				if t1_7745c5c3_Err != nil {
					return t1_7745c5c3_Err
				}
				if !t1_7745c5c3_IsBuffer {
					_, t1_7745c5c3_Err = io.Copy(t1_7745c5c3_W, t1_7745c5c3_Buffer)
				}
				return t1_7745c5c3_Err
			})
			t1_7745c5c3_Err = wrapper(2).Render(t1.WithChildren(ctx, t1_7745c5c3_Var4), t1_7745c5c3_Buffer)
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
			if !t1_7745c5c3_IsBuffer {
				_, t1_7745c5c3_Err = io.Copy(t1_7745c5c3_W, t1_7745c5c3_Buffer)
			}
			return t1_7745c5c3_Err
		})
		t1_7745c5c3_Err = wrapper(1).Render(t1.WithChildren(ctx, t1_7745c5c3_Var3), t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
