// Code generated by t1 - DO NOT EDIT.

package testcssexpression

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/t1"
import "strings"

func className() t1.CSSClass {
	var t1_7745c5c3_CSSBuilder strings.Builder
	t1_7745c5c3_CSSBuilder.WriteString(`background-color:#ffffff;`)
	t1_7745c5c3_CSSBuilder.WriteString(`max-height:calc(100vh - 170px);`)
	t1_7745c5c3_CSSBuilder.WriteString(string(t1.SanitizeCSS(`color`, red)))
	t1_7745c5c3_CSSID := t1.CSSID(`className`, t1_7745c5c3_CSSBuilder.String())
	return t1.ComponentCSSClass{
		ID:    t1_7745c5c3_CSSID,
		Class: t1.SafeCSS(`.` + t1_7745c5c3_CSSID + `{` + t1_7745c5c3_CSSBuilder.String() + `}`),
	}
}
