// Code generated by t1 - DO NOT EDIT.

package testscriptinline

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/t1"
import "context"
import "io"
import "bytes"

func withParameters(a string, b string, c int) t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_withParameters_1056`,
		Function: `function __t1_withParameters_1056(a, b, c){console.log(a, b, c);
}`,
		Call:       t1.SafeScript(`__t1_withParameters_1056`, a, b, c),
		CallInline: t1.SafeScriptInline(`__t1_withParameters_1056`, a, b, c),
	}
}

func withoutParameters() t1.ComponentScript {
	return t1.ComponentScript{
		Name: `__t1_withoutParameters_6bbf`,
		Function: `function __t1_withoutParameters_6bbf(){alert("hello");
}`,
		Call:       t1.SafeScript(`__t1_withoutParameters_6bbf`),
		CallInline: t1.SafeScriptInline(`__t1_withoutParameters_6bbf`),
	}
}

func InlineJavascript(a string) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		t1_7745c5c3_Err = withoutParameters().Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = withParameters(a, "test", 123).Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = withoutParameters().Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		t1_7745c5c3_Err = withParameters(a, "test", 123).Render(ctx, t1_7745c5c3_Buffer)
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
