// Code generated by t1 - DO NOT EDIT.

package elseif

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/senforsce/tndr"
import "context"
import "io"
import "bytes"

func render(d data) t1.Component {
	return t1.ComponentFunc(func(ctx context.Context, t1_7745c5c3_W io.Writer) (t1_7745c5c3_Err error) {
		t1_7745c5c3_Buffer, t1_7745c5c3_IsBuffer := t1_7745c5c3_W.(*bytes.Buffer)
		if !t1_7745c5c3_IsBuffer {
			t1_7745c5c3_Buffer = t1.GetBuffer()
			defer t1.ReleaseBuffer(t1_7745c5c3_Buffer)
		}
		ctx = t1.InitializeContext(ctx)
		t1_7745c5c3_Var1 := t1.GetChildren(ctx)
		if t1_7745c5c3_Var1 == nil {
			t1_7745c5c3_Var1 = t1.NopComponent
		}
		ctx = t1.ClearChildren(ctx)
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("<div>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if d.IsTrue() {
			var t1_7745c5c3_Var2 string
			t1_7745c5c3_Var2, t1_7745c5c3_Err = t1.JoinStringErrs("True")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 5, Col: 11}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var2))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		} else if !d.IsTrue() {
			var t1_7745c5c3_Var3 string
			t1_7745c5c3_Var3, t1_7745c5c3_Err = t1.JoinStringErrs("False")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 7, Col: 12}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var3))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		} else {
			var t1_7745c5c3_Var4 string
			t1_7745c5c3_Var4, t1_7745c5c3_Err = t1.JoinStringErrs("Else")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 9, Col: 11}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var4))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</div><div>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if 1 == 2 {
			var t1_7745c5c3_Var5 string
			t1_7745c5c3_Var5, t1_7745c5c3_Err = t1.JoinStringErrs("If")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 14, Col: 9}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var5))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		} else if 1 == 1 {
			var t1_7745c5c3_Var6 string
			t1_7745c5c3_Var6, t1_7745c5c3_Err = t1.JoinStringErrs("ElseIf")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 16, Col: 13}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var6))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</div><div>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if 1 == 2 {
			var t1_7745c5c3_Var7 string
			t1_7745c5c3_Var7, t1_7745c5c3_Err = t1.JoinStringErrs("If")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 21, Col: 9}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var7))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		} else if 1 == 3 {
			var t1_7745c5c3_Var8 string
			t1_7745c5c3_Var8, t1_7745c5c3_Err = t1.JoinStringErrs("ElseIf")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 23, Col: 13}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var8))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		} else if 1 == 4 {
			var t1_7745c5c3_Var9 string
			t1_7745c5c3_Var9, t1_7745c5c3_Err = t1.JoinStringErrs("ElseIf")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 25, Col: 13}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var9))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		} else if 1 == 1 {
			var t1_7745c5c3_Var10 string
			t1_7745c5c3_Var10, t1_7745c5c3_Err = t1.JoinStringErrs("OK")
			if t1_7745c5c3_Err != nil {
				return t1.Error{Err: t1_7745c5c3_Err, FileName: `generator/test-elseif/template.t1`, Line: 27, Col: 9}
			}
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString(t1.EscapeString(t1_7745c5c3_Var10))
			if t1_7745c5c3_Err != nil {
				return t1_7745c5c3_Err
			}
		}
		_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteString("</div>")
		if t1_7745c5c3_Err != nil {
			return t1_7745c5c3_Err
		}
		if !t1_7745c5c3_IsBuffer {
			_, t1_7745c5c3_Err = t1_7745c5c3_Buffer.WriteTo(t1_7745c5c3_W)
		}
		return t1_7745c5c3_Err
	})
}
